language: php
php:
  - '5.6'
  - '7.0'

env:
- PRESTASHOP_VERSION=1.6.0.x
- PRESTASHOP_VERSION=1.6.1.x
  global:
    - VENDOR_DIR=modules/bliskapaczka/vendor
    - COMMIT=${TRAVIS_COMMIT::8}

matrix:
  exclude:
    - php: 7.0
      env: PRESTASHOP_VERSION=1.6.0.x

services:
  - docker

before_script:
  - composer install

script: 
  - $VENDOR_DIR/bin/phpcs -s --colors --standard=rules.xml --ignore=modules/bliskapaczka/vendor/* modules/
  - $VENDOR_DIR/bin/phpmd modules/ text codesize --exclude modules/bliskapaczka/vendor
  - $VENDOR_DIR/bin/phpcpd --exclude vendor modules/
  - $VENDOR_DIR/bin/phpdoccheck --directory=modules --exclude=bliskapaczka/tests,bliskapaczka/vendor
  - $VENDOR_DIR/bin/phploc modules/
  - $VENDOR_DIR/bin/phpunit --bootstrap modules/bliskapaczka/tests/bootstrap.php modules/bliskapaczka/tests/unit/

jobs:
  include:
    - stage: build
      script: 
        - docker build -t bliskapaczkapl/prestashop:$COMMIT -t bliskapaczkapl/prestashop:latest -f dev/docker/php-5.6/prestashop-1.6.1.x/Dockerfile .
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push bliskapaczkapl/prestashop:$COMMIT;
      php: 5.6
      env: PRESTASHOP_VERSION=1.6.1.x
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker push bliskapaczkapl/prestashop:latest;
          fi
        - if [ "$TRAVIS_BRANCH" == "develop" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker push bliskapaczkapl/prestashop:develop;
          fi
