version: "3"
services:
  prestashop:
    image: bliskapaczkapl/prestashop
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
     - ./dev/docker/mysql/env
    environment:
      DB_HOST: db
      DOMAIN: localhost:8080
    links:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
     - ./dev/docker/mysql/env